# Generated by Django 6.0 on 2026-01-16 18:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myport', '0002_catogry_alter_portfolio_image'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='catogry',
            new_name='category',
        ),
    ]
