# Generated by Django 6.0 on 2026-01-17 05:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myport', '0003_rename_catogry_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='phone',
        ),
    ]
