# Generated by Django 6.0 on 2026-01-17 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myport', '0004_remove_contact_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='subject',
            field=models.CharField(default='-', max_length=225, null=True),
        ),
    ]
